[matching]
'neomutt' = ''
'mpv' = ''
'/^reddit.*/'="樓"
'/.*YouTube.*/'="<span foreground='#CC0000'></span>"
'/.* – Netflix$/'="<span foreground='#EE0000'>ﱄ</span>"
'/^Netflix$/'="<span foreground='#EE0000'>ﱄ</span>"
'telegramdesktop'=''
'TelegramDesktop'=''
"libreoffice-writer"=''
'pulsemixer'='ﰝ'
"Notion"="ﴬ"
"notion-app-enhanced"="ﴬ"
"/^lf$/"=""
"ncmpcpp"="ﱘ"
'nmtui'=""
"Typora" = ""
"zathura"=""
"org.pwmt.zathura" = ""
"feh"=""
"Gimp"=""
"chromium"=""
"weechat"=""
