import:
  - /home/bibek/.config/alacritty/color.yml

live_config_reload: true

background_opacity: 0.9

font:
  normal:
    family: ShureTechMono Nerd Font
  size: 18.0
colors:
  # COLORSCHEME: gruvbox_dark.yaml
  # Default colors
  primary:
    # hard contrast: background = '0xf9f5d7'
    background: '0x282828'
    # soft contrast: background = '0x32302f'
    foreground: '0xebdbb2'

  # Normal colors
  normal:
    black: '0x282828'
    red: '0xcc241d'
    green: '0x98971a'
    yellow: '0xd79921'
    blue: '0x458588'
    magenta: '0xb16286'
    cyan: '0x689d6a'
    white: '0xa89984'

  # Bright colors
  bright:
    black: '0x928374'
    red: '0xfb4934'
    green: '0xb8bb26'
    yellow: '0xfabd2f'
    blue: '0x83a598'
    magenta: '0xd3869b'
    cyan: '0x8ec07c'
    white: '0xebdbb2'
  cursor:
    text: '0xeeeeee'
    cursor: '0x878787'

  # Normal colors
  search:
    matches:
      foreground: '0xb2b2b2'
      background: '0xb26818'
    focused_match:
      foreground: CellBackground
      background: CellForeground

  dim:
    black: '0x000000'
    red: '0xb21818'
    green: '0x18b218'
    yellow: '0xb26818'
    blue: '0x1818b2'
    magenta: '0xb218b2'
    cyan: '0x18b2b2'
    white: '0xb2b2b2'
